import React, { useState } from "react";
import style from "./country.module.css";
import { fetchGlobal } from "../../api";

const allCountries = [
  "Anguilla",
  "Antigua and Barbuda",
  "Aruba",
  "Bahamas",
  "Barbados",
  "Belize",
  "Bermuda",
  "British Virgin Islands",
  "Canada",
  "Caribbean Netherlands",
  "Cayman Islands",
  "Costa Rica",
  "Cuba",
  "Curaçao",
  "Dominica",
  "Dominican Republic",
  "El Salvador",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guatemala",
  "Haiti",
  "Honduras",
  "Jamaica",
  "Martinique",
  "Mexico",
  "Montserrat",
  "Nicaragua",
  "Panama",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre Miquelon",
  "Saint Vincent and the Grenadines",
  "Sint Maarten",
  "St. Barth",
  "Trinidad and Tobago",
  "Turks and Caicos Islands",
  "USA",
  "Afghanistan",
  "Armenia",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Bhutan",
  "Brunei",
  "Cambodia",
  "China",
  "Cyprus",
  "Georgia",
  "Hong Kong",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Israel",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Lebanon",
  "Macao",
  "Malaysia",
  "Maldives",
  "Mongolia",
  "Myanmar",
  "N. Korea",
  "Nepal",
  "Oman",
  "Pakistan",
  "Palestine",
  "Philippines",
  "Qatar",
  "S. Korea",
  "Saudi Arabia",
  "Singapore",
  "Sri Lanka",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Thailand",
  "Timor-Leste",
  "Turkey",
  "UAE",
  "Uzbekistan",
  "Vietnam",
  "Yemen",
  "Albania",
  "Andorra",
  "Austria",
  "Belarus",
  "Belgium",
  "Bosnia",
  "Bulgaria",
  "Channel Islands",
  "Croatia",
  "Czechia",
  "Denmark",
  "Estonia",
  "Faroe Islands",
  "Finland",
  "France",
  "Germany",
  "Gibraltar",
  "Greece",
  "Holy See (Vatican City State)",
  "Hungary",
  "Iceland",
  "Ireland",
  "Isle of Man",
  "Italy",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Malta",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Netherlands",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "San Marino",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "UK",
  "Ukraine",
  "Argentina",
  "Bolivia",
  "Brazil",
  "Chile",
  "Colombia",
  "Ecuador",
  "Falkland Islands (Malvinas)",
  "French Guiana",
  "Guyana",
  "Paraguay",
  "Peru",
  "Suriname",
  "Uruguay",
  "Venezuela",
  "Australia",
  "Cook Islands",
  "Fiji",
  "French Polynesia",
  "Kiribati",
  "Marshall Islands",
  "Micronesia",
  "Nauru",
  "New Caledonia",
  "New Zealand",
  "Niue",
  "Palau",
  "Papua New Guinea",
  "Samoa",
  "Solomon Islands",
  "Tokelau",
  "Tonga",
  "Tuvalu",
  "Vanuatu",
  "Wallis and Futuna",
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Congo",
  "Côte d'Ivoire",
  "DRC",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Rwanda",
  "Réunion",
  "Saint Helena",
  "Sao Tome and Principe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Swaziland",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Western Sahara",
  "Zambia",
  "Zimbabwe",
];

const Country = ({ setData }) => {
  const [country, setCountry] = useState("");

  const handleChange = async (e) => {
    const selectedCountry = e.target.value;
    setCountry(selectedCountry);

    try {
      let countryData;

      if (selectedCountry === "") {
        // Si "Global" est choisi
        countryData = await fetchGlobal();
      } else {
        const response = await fetch(
          `http://127.0.0.1:8000/api/country/${selectedCountry}/`
        );
        countryData = await response.json();
      }

      setData(countryData);
    } catch (error) {
      console.error("Erreur chargement des données:", error);
    }
  };

  return (
    <div className={style.countryContainer}>
      <select
        value={country}
        onChange={handleChange}
        className={style.countrySelect}
      >
        <option value="">Global</option>
        {allCountries.map((c) => (
          <option key={c} value={c}>
            {c}
          </option>
        ))}
      </select>
    </div>
  );
};

export default Country;
